<a href="https://colab.research.google.com/github/yeyomuri/curso_profesional_de_tensorflow/blob/main/MNIST_Keras_data_set.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Cargar librerias

In [ ]:
from tensorflow import keras
from tensorflow.keras import  layers
from tensorflow.keras.datasets import mnist


#Cargar Dataset

In [ ]:
(train_images, train_labels), (test_images, test_labels) = mnist.load_data()

11501568/11490434 [==============================] - 0s 0us/step


In [ ]:
train_images.shape


(60000, 28, 28)

In [ ]:
len(train_labels) 

60000

In [ ]:
train_labels

array([5, 0, 4, ..., 5, 6, 8], dtype=uint8)

In [ ]:
test_images.shape

(10000, 28, 28)

In [ ]:
len(test_labels)

10000

In [ ]:
train_labels

array([5, 0, 4, ..., 5, 6, 8], dtype=uint8)

#Arquitectura neuronal (the network architecture)

In [ ]:
model = keras.Sequential([
  layers.Dense(512, activation="relu"),
  layers.Dense(10, activation="softmax")
])

#Compile

In [ ]:
model.compile(optimizer="rmsprop", loss="sparse_categorical_crossentropy", metrics = ["accuracy"])

#Preparacion de datos

In [ ]:
train_images = train_images.reshape((60000, 28 * 28))
train_images = train_images.astype("float32") / 255 
test_images = test_images.reshape((10000, 28 * 28))
test_images = test_images.astype("float32") / 255


#Entrenamiento (Fitting model on Keras)


In [ ]:
model.fit(train_images, train_labels, epochs=5, batch_size=128)

Epoch 1/5
469/469 [==============================] - 6s 10ms/step - loss: 0.2552 - accuracy: 0.9262
Epoch 2/5
469/469 [==============================] - 5s 10ms/step - loss: 0.1035 - accuracy: 0.9698
Epoch 3/5
469/469 [==============================] - 5s 10ms/step - loss: 0.0693 - accuracy: 0.9790
Epoch 4/5
469/469 [==============================] - 5s 10ms/step - loss: 0.0502 - accuracy: 0.9850
Epoch 5/5
469/469 [==============================] - 5s 10ms/step - loss: 0.0379 - accuracy: 0.9885


#Predicciones a partir del modelo entrenado previo

In [ ]:
test_digits = test_images[0:10]
predictions = model.predict(test_digits)
predictions[0]

array([1.9252649e-08, 1.9991216e-10, 2.9035173e-06, 1.1387151e-03,
       4.7538126e-11, 6.1291665e-08, 9.7489853e-14, 9.9882787e-01,
       2.5040328e-07, 3.0131756e-05], dtype=float32)

In [ ]:
predictions[7].argmax()

9

In [ ]:
test_labels[7]

9

#Evaluando el modelo con datos externos

In [ ]:
test_loss, test_acc = model.evaluate(test_images, test_labels)

313/313 [==============================] - 1s 3ms/step - loss: 0.0737 - accuracy: 0.9776
